### ISSUE TITLE
Cache check fails when image open on first opening instanseg

### ISSUE THREAD

**Issue by alanocallaghan** [qupath/qupath-extension-instanseg#116]
Steps to reproduce:

1. Run QuPath
2. Open image
3. Open instanseg window

Error:

```
java.lang.NullPointerException: null
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at java.base/java.util.ImmutableCollections.listFromArray(ImmutableCollections.java:192)
	at java.base/java.util.List.of(List.java:1172)
	at java.base/java.util.ImmutableCollections.listCopy(ImmutableCollections.java:174)
	at java.base/java.util.List.copyOf(List.java:1193)
	at qupath.ext.instanseg.ui.CheckModelCache.snapshotChecks(CheckModelCache.java:111)
	at qupath.ext.instanseg.ui.InstanSegController.updateInputChannels(InstanSegController.java:355)
	at qupath.ext.instanseg.ui.InstanSegController.handleImageDataChange(InstanSegController.java:335)
	at qupath.ext.instanseg.ui.InstanSegController.configureInputChannelCombo(InstanSegController.java:316)
	at qupath.ext.instanseg.ui.InstanSegController.<init>(InstanSegController.java:197)
```

Doesn't happen when opening instanseg window before opening an image. Issue is that `checkbox.getCheckModel().getCheckedItems()` is:

```
[null, null, null]
```

Can refactor the class to use indices instead but this leads to a <0 index error so suspect something else is afoot.

**Comment by petebankhead** [comment]
Can you check which version of ControlsFX you have on the classpath?
See this commit suggesting that the problem might occur if ControlsFX 11.2.1 is there (e.g. brought in via the extension manager, or some other dependency): https://github.com/qupath/qupath/commit/121bd5752e3f600ce9dfa67d5c81acc29a256beb

**Comment by alanocallaghan** [comment]
Ah yeah it'll be the extension manager
