### ISSUE TITLE
download error

### ISSUE THREAD

**Issue by r100gs** [qupath/qupath-extension-instanseg#93]
Hello,

I wanted to try the instanseg-plugin but get following error with zip version of qupath 0.6

Can I change the download folder?

Best regards,
Stefan

````
Failed to download PyTorch native library
ai.djl.engine.EngineException: Failed to download PyTorch native library
	at ai.djl.pytorch.jni.LibUtils.downloadPyTorch(LibUtils.java:508)
	at ai.djl.pytorch.jni.LibUtils.findNativeLibrary(LibUtils.java:318)
	at ai.djl.pytorch.jni.LibUtils.getLibTorch(LibUtils.java:93)
	at ai.djl.pytorch.jni.LibUtils.loadLibrary(LibUtils.java:81)
	at ai.djl.pytorch.engine.PtEngine.newInstance(PtEngine.java:53)
	at ai.djl.pytorch.engine.PtEngineProvider.getEngine(PtEngineProvider.java:41)
	at ai.djl.engine.Engine.getEngine(Engine.java:190)
	at qupath.ext.instanseg.core.PytorchManager.lambda$getEngineOnline$0(PytorchManager.java:28)
	at qupath.ext.instanseg.core.PytorchManager.callWithTempProperty(PytorchManager.java:114)
	at qupath.ext.instanseg.core.PytorchManager.callOnline(PytorchManager.java:106)
	at qupath.ext.instanseg.core.PytorchManager.getEngineOnline(PytorchManager.java:28)
	at qupath.ext.instanseg.ui.InstanSegController.downloadPyTorch(InstanSegController.java:826)
	at qupath.ext.instanseg.ui.InstanSegController.ensurePyTorchAvailable(InstanSegController.java:815)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.nio.file.AccessDeniedException: C:\Users\soellnsn\.djl.ai\pytorch\tmp13809347405202496542 -> C:\Users\soellnsn\.djl.ai\pytorch\2.3.1-cpu-win-x86_64
	at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileCopy.move(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.move(Unknown Source)
	at java.base/java.nio.file.Files.move(Unknown Source)
	at ai.djl.util.Utils.moveQuietly(Utils.java:133)
	at ai.djl.pytorch.jni.LibUtils.downloadPyTorch(LibUtils.java:505)
	... 19 more

````

**Comment by petebankhead** [comment]
This extension doesn't make any changes to DeepJavaLibrary's default behavior. Therefore you should be able to change the location by following their instructions and setting an environment variable: http://djl.ai/docs/development/cache_management.html

**Comment by r100gs** [comment]
Thank you!
